#! /usr/bin/env perl

# sub on_action {
sub on_user_command {
  my ($term, $cmd) = @_;
  if ($cmd eq "dolphin:open") {
    my $dir = readlink("/proc/" . $term->{child_pid} . "/cwd");
    `dolphin $dir &` ;
  }
}

sub on_child_start {
  my ($term, $pid) = @_;
  $term->{child_pid} = $pid;
  ()
}
