#! /bin/bash
sudo apt install -y \
	apt-transport-https \
	ca-certificates \
	curl \
	software-properties-common

# add docker's official GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# add docker's stable repository
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

# # add neovim ppa # use nix instead
# sudo add-apt-repository ppa:neovim-ppa/stable

# add emacs ppa
sudo add-apt-repository ppa:kelleyk/emacs

# add dbeaver ppa
sudo add-apt-repository ppa:serge-rider/dbeaver-ce

# golang
# sudo add-apt-repository ppa:gophers/archive

sudo apt-get update
