#! /bin/bash

# update the system
sudo apt-get update

# dependencies
sudo apt install -y \
  libreadline-dev \
  libssl-dev \
  python3-dev \
  python-dev \
  zlib1g-dev

# todo: fix this. needed it for asdf-php
sudo apt install curl build-essential libjpeg-dev libpng-dev openssl libcurl4-openssl-dev pkg-config libedit-dev zlib1g-dev libicu-dev libxml2-dev gettext bison libmysqlclient-dev libpq-dev


# packages
sudo apt install -y \
  acpi \
  arandr \
  auctex \
  autoconf \
  # blueman \
  calibre \
  compton \
  conky \
  curl \
  dbeaver-ce \
  docker-ce \
  dolphin \
  dunst \
  dzen2 \
  emacs26 \
  entr \
  espeak \
  feh \
  filezilla \
  git \
  gnome-dictionary \
  gnome-power-manager \
  gnome-settings-daemon \
  # golang-1.10-go \
  graphviz \
  gtk-chtheme \
  # haskell-platform \
  i3 \
  jq \
  # kde-plasma-desktop \
  kde-standard \
  konsole \
  libmariadbclient18 \
  libreswan \
  libsqlite3-dev \
  lxappearance \
  mariadb-client \
  # mariadb-server \
  # mongodb \
  # mongodb-clients \
  mpc \
  mpd \
  mplayer \
  mycli \
  # mysql-workbench \
  ncmpcpp \
  neovim \
  openbox \
  oxygen-icon-theme \
  pasystray \
  pcmanfm \
  # percona-xtradb-cluster-server-5.7 \
  pnmixer \
  pwgen \
  python3-pip \
  python-pip \
  # qt4-qtconfig \
  ranger \
  redshift \
  repo \
  rofi \
  rxvt-unicode \
  scrot \
  slock \
  sqlite3 \
  stalonetray \
  stow \
  taffybar \
  texlive \
  texlive-fonts-extra
  texlive-latex-extra \
  texlive-xetex \
  tig \
  tint2 \
  tmux \
  trayer \
  tree \
  unclutter \
  virtualbox \
  wmctrl \
  xbacklight \
  xclip \
  # xfce4-power-manager \
  xmobar \
  xmonad \
  xsettingsd \
  xterm \
  zsh
