#! /bin/bash

# update the system
sudo apt-get update

# dependencies
sudo apt install -y \
	libreadline-dev \
	libssl-dev \
	python3-dev \
	python-dev \
	zlib1g-dev


# packages
sudo apt install -y \
	arandr \
	curl \
	docker-ce \
	emacs \
	git \
	i3 \
	neovim \
	python3-pip \
	python-pip \
	stow \
	tmux \
	zsh
