#! /bin/bash

# update the system
sudo apt-get update

# dependencies
sudo apt install -y \
	libreadline-dev \
	libssl-dev \
	python3-dev \
	python-dev \
	zlib1g-dev


# packages
sudo apt install -y \
	arandr \
  blueman \
  calibre \
	curl \
	docker-ce \
  dolphin \
  dunst \
	emacs26 \
  exuberant-ctags \
  feh \
	git \
  gnome-power-manager \
  gnome-settings-daemon \
	gtk-chtheme \
  haskell-platform \
	i3 \
  konsole \
	lxappearance \
  mpd \
  mpc \
  ncmpcpp \
	neovim \
  oxygen-icon-theme \
  pasystray \
  pcmanfm \
	python3-pip \
	python-pip \
	qt4-qtconfig \
  rxvt-unicode \
  scrot \
  slock \
	stow \
	tmux \
  tree \
  xsettingsd \
  xterm \
	zsh
