#! /bin/bash

# update the system
sudo apt-get update

# dependencies
sudo apt install -y \
     libreadline-dev \
     libssl-dev \
     python3-dev \
     python-dev \
     zlib1g-dev


# packages
sudo apt install -y \
     acpi \
     arandr \
     blueman \
     calibre \
     conky \
     curl \
     dbeaver-ce \
     docker-ce \
     dolphin \
     dzen2 \
     dunst \
     emacs26 \
     # exuberant-ctags \
     feh \
     git \
     gnome-power-manager \
     gnome-settings-daemon \
     gtk-chtheme \
     # haskell-platform \
     i3 \
     kde-plasma-desktop \
     konsole \
     lxappearance \
     # mongodb \
     # mongodb-clients \
     mpd \
     mplayer \
     mpc \
     ncmpcpp \
     neovim \
     oxygen-icon-theme \
     pasystray \
     pcmanfm \
     python3-pip \
     python-pip \
     qt4-qtconfig \
     ranger \
     redshift \
     rofi \
     rxvt-unicode \
     scrot \
     slock \
     stow \
     tmux \
     tree \
     unclutter \
     xmonad \
     xmobar \
     xsettingsd \
     xterm \
	   zsh
