#! /bin/bash

# update the system
sudo apt-get update

# dependencies
sudo apt install -y \
	libreadline-dev \
	libssl-dev \
	python3-dev \
	python-dev \
	zlib1g-dev


# packages
sudo apt install -y \
	arandr \
	curl \
	docker-ce \
  dolphin \
	emacs26 \
  exuberant-ctags \
	git \
	i3 \
	lxappearance \
	gtk-chtheme \
  konsole \
	qt4-qtconfig \
	neovim \
  pcmanfm \
	python3-pip \
	python-pip \
  rxvt-unicode \
	stow \
	tmux \
  tree \
  xterm \
	zsh
