#! /bin/bash

# for rbenv's ruby-build
brew install openssl readline

brew install \
  coreutils \
  curl \
  git \
  graphviz \
  jenv \
  maven \
  neovim \
  pwgen \
  pyenv \
  python3 \
  ripgrep \
  sqlite \
  stow \
  tmux \
  tree \
  wget \
  zlib \
  zsh

brew install --HEAD universal-ctags/universal-ctags/universal-ctags

brew cask install \
  emacs \
  iterm2
