#! /bin/bash

# for rbenv's ruby-build
brew install openssl readline

brew install \
  cmake \
  coreutils \
  curl \
  findutils \
  git \
  graphviz \
  jenv \
  jq \
  luarocks \
  mpv \
  neovim \
  pwgen \
  pyenv \
  python3 \
  ripgrep \
  sqlite \
  stow \
  tmux \
  tree \
  wget \
  zlib \
  zsh

brew install --HEAD universal-ctags/universal-ctags/universal-ctags

brew cask install \
  mactex \
  emacs \
  iterm2

brew tap homebrew/cask-fonts
brew cask install \
  font-inconsolata \
  font-hack \
  font-fira-code \
  font-source-code-pro
