#! /bin/bash
# don't use graphical login (gdm)
sudo systemctl set-default multi-user.target # to revert: sudo systemctl set-default graphical.target

# avoid having to run sudo before every docker command
sudo usermod -aG docker ${USER}

# use zsh
chsh -s $(which zsh)
