#! /bin/bash

# nodejs
asdf plugin-add nodejs
asdf install nodejs 12.13.0
asdf global nodejs 12.13.0

# java
asdf plugin-add java
# java 11 is currently not on asdf, so i uninstalled those below so that /usr/local/bin/java would have priority
asdf install java oracle-8.181
# asdf install java oracle-10.0.2
# asdf global java oracle-10.0.2

# maven
asdf plugin-add maven
asdf install maven 3.6.0
asdf global maven 3.6.0

# gradle
asdf plugin-add gradle
asdf install gradle 4.9
asdf install gradle 5.1
asdf global gradle 5.1

# python
asdf plugin-add python
asdf install python 3.7.2
asdf global python 3.7.2


# ruby
asdf plugin-add ruby
asdf install ruby 2.5.1
asdf install ruby jruby-9.2.0.0
asdf global ruby 2.5.1

# php
asdf plugin-add php
asdf install php 5.6.40
asdf install php 7.0.33
asdf install php 7.1.23
asdf install php 7.2.11
asdf global php 7.2.11

# dotnet core
# asdf plugin-add dotnet-core https://github.com/emersonsoares/asdf-dotnet-core.git
# asdf install dotnet-core 2.1.403
# asdf global dotnet-core 2.1.403
