#! /bin/bash

# nodejs
asdf plugin-add nodejs
asdf install nodejs 8.12.0
asdf global nodejs 8.12.0

# java
asdf plugin-add java
asdf install java oracle-8.181
asdf global java oracle-8.181
# asdf install java oracle-10.0.2
# asdf global java oracle-10.0.2

# gradle
asdf plugin-add gradle
asdf install gradle 4.9
asdf global gradle 4.9

# ruby
asdf plugin-add ruby
asdf install ruby 2.5.1
asdf global ruby 2.5.1

# php
asdf plugin-add php
asdf install php 7.1.23
asdf install php 7.2.11
asdf global php 7.2.11

# dotnet core
asdf plugin-add dotnet-core https://github.com/emersonsoares/asdf-dotnet-core.git
asdf install dotnet-core 2.1.403
asdf global dotnet-core 2.1.403
