#! /usr/bin/env bash

echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

# this didn't work with curl originally.
# i had to wget the file, then pass it to apt-key:
#     wget ...apt-key.gpg && sudo apt-key add apt-key.gpg
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

sudo apt-get update \
  && sudo apt-get install -y \
    google-cloud-sdk \
    kubectl
